/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    'event-series': EventSery;
    actualites: Actualite;
    games: Game;
    categories: Category;
    partners: Partner;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    'event-series': EventSeriesSelect<false> | EventSeriesSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'collectivites-page': CollectivitesPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'collectivites-page': CollectivitesPageSelect<false> | CollectivitesPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Événements et tournois ponctuels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Adresse de la page : /evenements/<identifiant>.
   */
  slug: string;
  title: string;
  type: 'tournoi' | 'event' | 'both';
  color: string;
  startDate: string;
  /**
   * À renseigner uniquement si l’événement dure plusieurs jours.
   */
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  /**
   * Adresse utilisée pour la carte et l’itinéraire.
   */
  location?: string | null;
  isCancelled?: boolean | null;
  cardThumbnail?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  heroBanner?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  heroBannerMobile?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  /**
   * Sélectionnez les partenaires à afficher. Pour en ajouter un au catalogue, passez par Référentiels → Partenaires.
   */
  partners?: (string | Partner)[] | null;
  description?:
    | (
        | {
            content?:
              | (
                  | {
                      title: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'title';
                    }
                  | {
                      paragraphs?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'paragraph';
                    }
                  | {
                      items?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'list';
                    }
                  | {
                      citationText: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'citation';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            stats?:
              | {
                  value: number;
                  type?: ('number' | 'euros') | null;
                  plus?: boolean | null;
                  label: string;
                  sublabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            images?:
              | {
                  image?: {
                    /**
                     * Envoyez une image pour remplacer celle d'origine.
                     */
                    media?: (string | null) | Media;
                    /**
                     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
                     */
                    path?: string | null;
                    /**
                     * Décrit l'image pour l'accessibilité et le référencement.
                     */
                    alt?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  categories?: (string | Category)[] | null;
  games?: (string | Game)[] | null;
  freeplayGames?: (string | Game)[] | null;
  randomizeFreeplayGames?: boolean | null;
  registrationOpen?: boolean | null;
  /**
   * Collez ici le code fourni par Weezevent pour la billetterie de cet événement.
   */
  weezeventCode?: string | null;
  /**
   * Laisser vide si aucune information de transport n’est à afficher.
   */
  transports?: {
    metro?:
      | {
          lines?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          station: string;
          walkTimeInMin: number;
          id?: string | null;
        }[]
      | null;
    bus?:
      | {
          lines?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          station: string;
          walkTimeInMin: number;
          id?: string | null;
        }[]
      | null;
    tramway?:
      | {
          lines?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          station: string;
          walkTimeInMin: number;
          id?: string | null;
        }[]
      | null;
    car?: {
      parkings?:
        | {
            name: string;
            address: string;
            distanceInMeters: number;
            walkTimeInMin: number;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images et fichiers utilisés dans le contenu du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Décrit l'image pour les lecteurs d'écran et le référencement. Peut être surchargé à l'endroit où l'image est utilisée.
   */
  alt?: string | null;
  credit?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos des partenaires, réutilisables sur les événements et dans les sections « Partenaires ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  /**
   * Sert aussi de texte alternatif au logo, pour l’accessibilité et le référencement.
   */
  name: string;
  /**
   * Envoyez le logo depuis la bibliothèque de médias. Le nom du partenaire ci-dessus lui sert de texte alternatif. Tant qu’aucun logo n’est envoyé, le partenaire n’apparaît pas sur le site.
   */
  logo?: (string | null) | Media;
  /**
   * Facultatif. Non utilisé par le site aujourd’hui — les logos ne sont pas cliquables.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Familles d'événements (Gaming House Tour, FIFA Season…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Identifiant de la catégorie (ex. « gamingHouseTour »). Utilisé dans les filtres d'URL.
   */
  slug: string;
  name: string;
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catalogue des jeux proposés en tournoi et en free play.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: string;
  /**
   * Identifiant du jeu (ex. « fortnite »). Référencé par les événements.
   */
  slug: string;
  name: string;
  /**
   * Une vignette illustrée nécessite un logo et des visuels ci-dessous.
   */
  blockType: 'block' | 'text';
  bgType?: ('gradient' | 'color') | null;
  color1?: string | null;
  color2?: string | null;
  logo?: {
    media?: (string | null) | Media;
  };
  img?: {
    media?: (string | null) | Media;
  };
  bgImg?: {
    media?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Tournées et séries déclinées en plusieurs étapes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-series".
 */
export interface EventSery {
  id: string;
  /**
   * Adresse de la page : /evenements/<identifiant>.
   */
  slug: string;
  title: string;
  color: string;
  isCancelled?: boolean | null;
  cardThumbnail?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  heroBanner?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  heroBannerMobile?: {
    /**
     * Envoyez une image pour remplacer celle d'origine.
     */
    media?: (string | null) | Media;
    /**
     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
     */
    path?: string | null;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
  };
  /**
   * Sélectionnez les partenaires à afficher. Pour en ajouter un au catalogue, passez par Référentiels → Partenaires.
   */
  partners?: (string | Partner)[] | null;
  /**
   * Contenu affiché sur la page de la série et repris par les étapes qui n’ont pas leur propre description.
   */
  description?:
    | (
        | {
            content?:
              | (
                  | {
                      title: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'title';
                    }
                  | {
                      paragraphs?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'paragraph';
                    }
                  | {
                      items?:
                        | {
                            text: string;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'list';
                    }
                  | {
                      citationText: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'citation';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            stats?:
              | {
                  value: number;
                  type?: ('number' | 'euros') | null;
                  plus?: boolean | null;
                  label: string;
                  sublabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            images?:
              | {
                  image?: {
                    /**
                     * Envoyez une image pour remplacer celle d'origine.
                     */
                    media?: (string | null) | Media;
                    /**
                     * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
                     */
                    path?: string | null;
                    /**
                     * Décrit l'image pour l'accessibilité et le référencement.
                     */
                    alt?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  games?: (string | Game)[] | null;
  freeplayGames?: (string | Game)[] | null;
  /**
   * Chaque étape hérite des visuels et du contenu de la série ; ne remplissez que ce qui change.
   */
  dates?:
    | {
        /**
         * Adresse : /evenements/<série>/<identifiant d’étape>.
         */
        slug: string;
        title?: string | null;
        startDate: string;
        endDate?: string | null;
        startTime?: string | null;
        endTime?: string | null;
        location: string;
        isCancelled?: boolean | null;
        cardThumbnail?: {
          /**
           * Envoyez une image pour remplacer celle d'origine.
           */
          media?: (string | null) | Media;
          /**
           * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
           */
          path?: string | null;
          /**
           * Décrit l'image pour l'accessibilité et le référencement.
           */
          alt?: string | null;
        };
        heroBanner?: {
          /**
           * Envoyez une image pour remplacer celle d'origine.
           */
          media?: (string | null) | Media;
          /**
           * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
           */
          path?: string | null;
          /**
           * Décrit l'image pour l'accessibilité et le référencement.
           */
          alt?: string | null;
        };
        heroBannerMobile?: {
          /**
           * Envoyez une image pour remplacer celle d'origine.
           */
          media?: (string | null) | Media;
          /**
           * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
           */
          path?: string | null;
          /**
           * Décrit l'image pour l'accessibilité et le référencement.
           */
          alt?: string | null;
        };
        description?:
          | (
              | {
                  content?:
                    | (
                        | {
                            title: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'title';
                          }
                        | {
                            paragraphs?:
                              | {
                                  text: string;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'paragraph';
                          }
                        | {
                            items?:
                              | {
                                  text: string;
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'list';
                          }
                        | {
                            citationText: string;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'citation';
                          }
                      )[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'text';
                }
              | {
                  stats?:
                    | {
                        value: number;
                        type?: ('number' | 'euros') | null;
                        plus?: boolean | null;
                        label: string;
                        sublabel?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'statistics';
                }
              | {
                  title?: string | null;
                  subtitle?: string | null;
                  images?:
                    | {
                        image?: {
                          /**
                           * Envoyez une image pour remplacer celle d'origine.
                           */
                          media?: (string | null) | Media;
                          /**
                           * Image d'origine du site (/assets/...). Ignorée dès qu'un fichier est envoyé ci-dessus.
                           */
                          path?: string | null;
                          /**
                           * Décrit l'image pour l'accessibilité et le référencement.
                           */
                          alt?: string | null;
                        };
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'gallery';
                }
            )[]
          | null;
        /**
         * Sélectionnez les partenaires à afficher. Pour en ajouter un au catalogue, passez par Référentiels → Partenaires.
         */
        partners?: (string | Partner)[] | null;
        games?: (string | Game)[] | null;
        freeplayGames?: (string | Game)[] | null;
        registrationOpen?: boolean | null;
        weezeventCode?: string | null;
        /**
         * Laisser vide si aucune information de transport n’est à afficher.
         */
        transports?: {
          metro?:
            | {
                lines?:
                  | {
                      value: string;
                      id?: string | null;
                    }[]
                  | null;
                station: string;
                walkTimeInMin: number;
                id?: string | null;
              }[]
            | null;
          bus?:
            | {
                lines?:
                  | {
                      value: string;
                      id?: string | null;
                    }[]
                  | null;
                station: string;
                walkTimeInMin: number;
                id?: string | null;
              }[]
            | null;
          tramway?:
            | {
                lines?:
                  | {
                      value: string;
                      id?: string | null;
                    }[]
                  | null;
                station: string;
                walkTimeInMin: number;
                id?: string | null;
              }[]
            | null;
          car?: {
            parkings?:
              | {
                  name: string;
                  address: string;
                  distanceInMeters: number;
                  walkTimeInMin: number;
                  id?: string | null;
                }[]
              | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Annonces mises en avant sur la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: string;
  /**
   * Identifiant de l’actualité.
   */
  slug: string;
  date: string;
  title: string;
  subtitle?: string | null;
  content?:
    | (
        | {
            title: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'title';
          }
        | {
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            citationText: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'citation';
          }
      )[]
    | null;
  image?: {
    media?: (string | null) | Media;
    /**
     * Décrit l'image pour l'accessibilité et le référencement.
     */
    alt?: string | null;
    position?: ('left' | 'right') | null;
  };
  /**
   * Facultatif — laissez le libellé vide pour ne rien afficher.
   */
  cta?: {
    label?: string | null;
    type?: ('standard' | 'weezevent') | null;
    url?: string | null;
    isExternal?: boolean | null;
    weezeventCode?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Comptes autorisés à se connecter au backoffice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Un éditeur gère le contenu du site mais ne peut pas créer de comptes.
   */
  role: 'admin' | 'editeur';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'event-series';
        value: string | EventSery;
      } | null)
    | ({
        relationTo: 'actualites';
        value: string | Actualite;
      } | null)
    | ({
        relationTo: 'games';
        value: string | Game;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  type?: T;
  color?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  isCancelled?: T;
  cardThumbnail?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  heroBanner?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  heroBannerMobile?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  partners?: T;
  description?:
    | T
    | {
        text?:
          | T
          | {
              content?:
                | T
                | {
                    title?:
                      | T
                      | {
                          title?: T;
                          id?: T;
                          blockName?: T;
                        };
                    paragraph?:
                      | T
                      | {
                          paragraphs?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    list?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    citation?:
                      | T
                      | {
                          citationText?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              stats?:
                | T
                | {
                    value?: T;
                    type?: T;
                    plus?: T;
                    label?: T;
                    sublabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              subtitle?: T;
              images?:
                | T
                | {
                    image?:
                      | T
                      | {
                          media?: T;
                          path?: T;
                          alt?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  categories?: T;
  games?: T;
  freeplayGames?: T;
  randomizeFreeplayGames?: T;
  registrationOpen?: T;
  weezeventCode?: T;
  transports?:
    | T
    | {
        metro?:
          | T
          | {
              lines?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              station?: T;
              walkTimeInMin?: T;
              id?: T;
            };
        bus?:
          | T
          | {
              lines?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              station?: T;
              walkTimeInMin?: T;
              id?: T;
            };
        tramway?:
          | T
          | {
              lines?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              station?: T;
              walkTimeInMin?: T;
              id?: T;
            };
        car?:
          | T
          | {
              parkings?:
                | T
                | {
                    name?: T;
                    address?: T;
                    distanceInMeters?: T;
                    walkTimeInMin?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-series_select".
 */
export interface EventSeriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  color?: T;
  isCancelled?: T;
  cardThumbnail?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  heroBanner?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  heroBannerMobile?:
    | T
    | {
        media?: T;
        path?: T;
        alt?: T;
      };
  partners?: T;
  description?:
    | T
    | {
        text?:
          | T
          | {
              content?:
                | T
                | {
                    title?:
                      | T
                      | {
                          title?: T;
                          id?: T;
                          blockName?: T;
                        };
                    paragraph?:
                      | T
                      | {
                          paragraphs?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    list?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    citation?:
                      | T
                      | {
                          citationText?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        statistics?:
          | T
          | {
              stats?:
                | T
                | {
                    value?: T;
                    type?: T;
                    plus?: T;
                    label?: T;
                    sublabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              subtitle?: T;
              images?:
                | T
                | {
                    image?:
                      | T
                      | {
                          media?: T;
                          path?: T;
                          alt?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  games?: T;
  freeplayGames?: T;
  dates?:
    | T
    | {
        slug?: T;
        title?: T;
        startDate?: T;
        endDate?: T;
        startTime?: T;
        endTime?: T;
        location?: T;
        isCancelled?: T;
        cardThumbnail?:
          | T
          | {
              media?: T;
              path?: T;
              alt?: T;
            };
        heroBanner?:
          | T
          | {
              media?: T;
              path?: T;
              alt?: T;
            };
        heroBannerMobile?:
          | T
          | {
              media?: T;
              path?: T;
              alt?: T;
            };
        description?:
          | T
          | {
              text?:
                | T
                | {
                    content?:
                      | T
                      | {
                          title?:
                            | T
                            | {
                                title?: T;
                                id?: T;
                                blockName?: T;
                              };
                          paragraph?:
                            | T
                            | {
                                paragraphs?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          list?:
                            | T
                            | {
                                items?:
                                  | T
                                  | {
                                      text?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          citation?:
                            | T
                            | {
                                citationText?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              statistics?:
                | T
                | {
                    stats?:
                      | T
                      | {
                          value?: T;
                          type?: T;
                          plus?: T;
                          label?: T;
                          sublabel?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              gallery?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    images?:
                      | T
                      | {
                          image?:
                            | T
                            | {
                                media?: T;
                                path?: T;
                                alt?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        partners?: T;
        games?: T;
        freeplayGames?: T;
        registrationOpen?: T;
        weezeventCode?: T;
        transports?:
          | T
          | {
              metro?:
                | T
                | {
                    lines?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    station?: T;
                    walkTimeInMin?: T;
                    id?: T;
                  };
              bus?:
                | T
                | {
                    lines?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    station?: T;
                    walkTimeInMin?: T;
                    id?: T;
                  };
              tramway?:
                | T
                | {
                    lines?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    station?: T;
                    walkTimeInMin?: T;
                    id?: T;
                  };
              car?:
                | T
                | {
                    parkings?:
                      | T
                      | {
                          name?: T;
                          address?: T;
                          distanceInMeters?: T;
                          walkTimeInMin?: T;
                          id?: T;
                        };
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  slug?: T;
  date?: T;
  title?: T;
  subtitle?: T;
  content?:
    | T
    | {
        title?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        citation?:
          | T
          | {
              citationText?: T;
              id?: T;
              blockName?: T;
            };
      };
  image?:
    | T
    | {
        media?: T;
        alt?: T;
        position?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        isExternal?: T;
        weezeventCode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  blockType?: T;
  bgType?: T;
  color1?: T;
  color2?: T;
  logo?:
    | T
    | {
        media?: T;
      };
  img?:
    | T
    | {
        media?: T;
      };
  bgImg?:
    | T
    | {
        media?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textes et images de la page d’accueil destinée aux joueurs (/).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero?: {
    /**
     * Texte animé au-dessus du titre. Les espaces sont conservés.
     */
    subtitle?: string | null;
    titleLine1?: string | null;
    /**
     * Affichée plus grande, dans la couleur d’accent.
     */
    titleLine2?: string | null;
    /**
     * Le premier bouton est mis en avant, le second est secondaire.
     */
    buttons?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Ex. « 80.000 ».
     */
    totalParticipants?: string | null;
    /**
     * Affiché dans « visiteurs/participants depuis … ».
     */
    participantsSince?: number | null;
    /**
     * Visuel très atténué, affiché en haut du bandeau.
     */
    backgroundImage?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
  };
  gamingSpaces?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Affichés par 3 sur une ligne à partir de la tablette.
     */
    cards?:
      | {
          logo?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          /**
           * Affichée en transparence derrière le logo.
           */
          backgroundImage?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          text: string;
          /**
           * La carte reste affichée, mais grisée et accompagnée de la mention « Indisponible pour le moment ».
           */
          unavailable?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  games?: {
    title?: string | null;
    intro?: string | null;
    /**
     * Sélectionnez les jeux dans le référentiel (Référentiels → Jeux), dans l’ordre d’affichage. Chaque carte mène aux événements filtrés sur ce jeu.
     */
    selection?: (string | Game)[] | null;
  };
  howItWorks?: {
    title?: string | null;
    steps?:
      | {
          /**
           * Sans icône, un pictogramme calendrier est affiché. Privilégiez une icône blanche.
           */
          icon?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          /**
           * Numéro compris, ex. « 1. Choisis ton event ».
           */
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whyJoin?: {
    title?: string | null;
    /**
     * Affichés par 4 sur une ligne sur PC.
     */
    cards?:
      | {
          /**
           * Visible sur PC uniquement, avant le survol.
           */
          image?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          /**
           * Seule illustration affichée sur mobile.
           */
          hoverImage?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          titleStart: string;
          titleAccent: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  figures?: {
    title?: string | null;
    /**
     * Affiché en première position, devant les chiffres.
     */
    logo?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    backgroundImage?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    /**
     * Chaque chiffre est animé au défilement, de 0 jusqu’à la valeur indiquée.
     */
    items?:
      | {
          value: number;
          /**
           * Ex. 1 pour afficher « 10,3 ».
           */
          decimals?: number | null;
          /**
           * Ex. « + de ».
           */
          prefix?: string | null;
          /**
           * Ex. « k » ou « k€ ».
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  community?: {
    title?: string | null;
    /**
     * Ex. « HGC ».
     */
    accent?: string | null;
    text?: string | null;
    /**
     * Détourée, affichée à droite sur PC et sous le texte sur mobile.
     */
    photo?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    backgroundImage?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    socials?:
      | {
          network: 'discord' | 'instagram' | 'facebook' | 'tiktok' | 'youtube';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    titleAccent?: string | null;
    title?: string | null;
    button: {
      label: string;
      href: string;
      id?: string | null;
    };
  };
  partners?: {
    subtitle?: string | null;
    title?: string | null;
    /**
     * Sélectionnez les partenaires dans le référentiel (Référentiels → Partenaires). Seuls ceux dont le logo a été envoyé apparaissent sur la page.
     */
    selection?: (string | Partner)[] | null;
  };
  /**
   * Titre et description affichés par Google et lors du partage sur les réseaux sociaux.
   */
  seo?: {
    /**
     * Environ 60 caractères.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes et images de la page d’accueil destinée aux collectivités (/collectivites).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collectivites-page".
 */
export interface CollectivitesPage {
  id: string;
  hero?: {
    titleLine1?: string | null;
    titleLine2?: string | null;
    titleLine3Start?: string | null;
    /**
     * Cette partie s’affiche dans la couleur d’accent.
     */
    titleLine3Accent?: string | null;
    intro?: string | null;
    /**
     * Visuel affiché en arrière-plan du bandeau, sous un dégradé sombre.
     */
    backgroundImage?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    /**
     * Le premier bouton est mis en avant, le second est secondaire.
     */
    buttons?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Bloc coloré à droite du titre. Renseignez soit une valeur, soit une icône.
     */
    highlights?:
      | {
          /**
           * Ex. « + de 5 ans ». Laissez vide si vous mettez une icône.
           */
          value?: string | null;
          /**
           * Les retours à la ligne sont conservés.
           */
          label: string;
          /**
           * Si une icône est fournie, elle remplace la valeur chiffrée.
           */
          icon?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Bandeau de photos défilant sous le titre. Comptez au moins 4 visuels pour un défilement fluide.
     */
    sliderImages?:
      | {
          image?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  whyUs?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Affichés sur une seule ligne à partir de 5 arguments ; au-delà, la grille passe à la ligne.
     */
    cards?:
      | {
          image?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          titleStart: string;
          titleAccent: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  figures?: {
    title?: string | null;
    backgroundImage?: {
      media?: (string | null) | Media;
      /**
       * Décrit l'image pour l'accessibilité et le référencement.
       */
      alt?: string | null;
    };
    /**
     * Chaque chiffre est animé au défilement, de 0 jusqu’à la valeur indiquée.
     */
    items?:
      | {
          value: number;
          /**
           * Ex. 1 pour afficher « 10,3 ».
           */
          decimals?: number | null;
          /**
           * Ex. « + de ».
           */
          prefix?: string | null;
          /**
           * Ex. « k » ou « k€ ».
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  solutions?: {
    title?: string | null;
    cards?:
      | {
          image?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          /**
           * Petite icône ronde en haut à gauche de la carte.
           */
          icon?: {
            media?: (string | null) | Media;
            /**
             * Décrit l'image pour l'accessibilité et le référencement.
             */
            alt?: string | null;
          };
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  testimonials: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
    button: {
      label: string;
      href: string;
      id?: string | null;
    };
    /**
     * Seul le premier témoignage est affiché pour le moment ; le compteur indique le total.
     */
    items?:
      | {
          quote: string;
          /**
           * Choisissez la collectivité dans le référentiel (Référentiels → Partenaires). Son logo et son nom servent de visuel et de texte alternatif ; tant qu’aucune n’est choisie, le témoignage s’affiche sans logo.
           */
          partner?: (string | null) | Partner;
          authorName: string;
          eventLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  partners?: {
    subtitle?: string | null;
    title?: string | null;
    /**
     * Sélectionnez les partenaires dans le référentiel (Référentiels → Partenaires). Seuls ceux dont le logo a été envoyé apparaissent sur la page.
     */
    selection?: (string | Partner)[] | null;
  };
  /**
   * Titre et description affichés par Google et lors du partage sur les réseaux sociaux.
   */
  seo?: {
    /**
     * Environ 60 caractères.
     */
    title?: string | null;
    /**
     * Environ 155 caractères.
     */
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        subtitle?: T;
        titleLine1?: T;
        titleLine2?: T;
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        totalParticipants?: T;
        participantsSince?: T;
        backgroundImage?:
          | T
          | {
              media?: T;
              alt?: T;
            };
      };
  gamingSpaces?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              logo?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              backgroundImage?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              text?: T;
              unavailable?: T;
              id?: T;
            };
      };
  games?:
    | T
    | {
        title?: T;
        intro?: T;
        selection?: T;
      };
  howItWorks?:
    | T
    | {
        title?: T;
        steps?:
          | T
          | {
              icon?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              title?: T;
              text?: T;
              id?: T;
            };
      };
  whyJoin?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              hoverImage?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              titleStart?: T;
              titleAccent?: T;
              text?: T;
              id?: T;
            };
      };
  figures?:
    | T
    | {
        title?: T;
        logo?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        backgroundImage?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        items?:
          | T
          | {
              value?: T;
              decimals?: T;
              prefix?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  community?:
    | T
    | {
        title?: T;
        accent?: T;
        text?: T;
        photo?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        backgroundImage?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        socials?:
          | T
          | {
              network?: T;
              url?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        titleAccent?: T;
        title?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  partners?:
    | T
    | {
        subtitle?: T;
        title?: T;
        selection?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collectivites-page_select".
 */
export interface CollectivitesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titleLine1?: T;
        titleLine2?: T;
        titleLine3Start?: T;
        titleLine3Accent?: T;
        intro?: T;
        backgroundImage?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        buttons?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        highlights?:
          | T
          | {
              value?: T;
              label?: T;
              icon?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              id?: T;
            };
        sliderImages?:
          | T
          | {
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              id?: T;
            };
      };
  whyUs?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              titleStart?: T;
              titleAccent?: T;
              text?: T;
              id?: T;
            };
      };
  figures?:
    | T
    | {
        title?: T;
        backgroundImage?:
          | T
          | {
              media?: T;
              alt?: T;
            };
        items?:
          | T
          | {
              value?: T;
              decimals?: T;
              prefix?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              image?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              icon?:
                | T
                | {
                    media?: T;
                    alt?: T;
                  };
              title?: T;
              text?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        items?:
          | T
          | {
              quote?: T;
              partner?: T;
              authorName?: T;
              eventLabel?: T;
              id?: T;
            };
      };
  partners?:
    | T
    | {
        subtitle?: T;
        title?: T;
        selection?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}